### ISSUE TITLE
Add Rails run tests to GitHub workflows

### ISSUE THREAD

**Issue by fezzopro** [fezzopro/task_manager#11]
```
name: Ruby

on: pull_request

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: 3.1.x
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
```
